export const REPORTS = 'REPORTS'
export const REPORT = 'REPORT'
export const ADDED_REPORT = 'ADDED_REPORT'
export const UPDATED_REPORT = 'UPDATED_REPORT'
export const DELETED_REPORT = 'DELETED_REPORT'

export const CHANGED_CALCULATOR = 'CHANGED_CALCULATOR'

export const ADDED_SCENARIO = 'ADDED_SCENARIO'
export const SCENARIO = 'SCENARIO'
export const UPDATED_SCENARIO = 'UPDATED_SCENARIO'
export const DELETED_SCENARIO = 'DELETED_SCENARIO'

export const ADDED_CASH_BUY = 'ADDED_CASH_BUY'
export const CASH_BUY = 'CASH_BUY'
export const UPDATED_CASH_BUY = 'UPDATED_CASH_BUY'

export const ADDED_NORMAL_PURCHASE = 'ADDED_NORMAL_PURCHASE'
export const NORMAL_PURCHASE = 'NORMAL_PURCHASE'
export const UPDATED_NORMAL_PURCHASE = 'UPDATED_NORMAL_PURCHASE'

export const ADDED_CASH_PURCHASE = 'ADDED_CASH_PURCHASE'
export const CASH_PURCHASE = 'CASH_PURCHASE'
export const UPDATED_CASH_PURCHASE = 'UPDATED_CASH_PURCHASE'

export const ADDED_SUB_TO_PURCHASE = 'ADDED_SUB_TO_PURCHASE'
export const SUB_TO_PURCHASE = 'SUB_TO_PURCHASE'
export const UPDATED_SUB_TO_PURCHASE = 'UPDATED_SUB_TO_PURCHASE'

export const ADDED_SELLER_FINANCE_PURCHASE = 'ADDED_SELLER_FINANCE_PURCHASE'
export const SELLER_FINANCE_PURCHASE = 'SELLER_FINANCE_PURCHASE'
export const UPDATED_SELLER_FINANCE_PURCHASE = 'UPDATED_SELLER_FINANCE_PURCHASE'
