export const REPORTS = 'REPORTS'
export const REPORT = 'REPORT'
export const ADDED_REPORT = 'ADDED_REPORT'
export const UPDATED_REPORT = 'UPDATED_REPORT'
export const DELETED_REPORT = 'DELETED_REPORT'

export const CHANGED_CALCULATOR = 'CHANGED_CALCULATOR'

export const ADDED_SCENARIO = 'ADDED_SCENARIO'
export const SCENARIO = 'SCENARIO'
export const UPDATED_SCENARIO = 'UPDATED_SCENARIO'
export const DELETED_SCENARIO = 'DELETED_SCENARIO'

export const ADDED_CASH_BUY = 'ADDED_CASH_BUY'
export const CASH_BUY = 'CASH_BUY'
export const UPDATED_CASH_BUY = 'UPDATED_CASH_BUY'

export const ADDED_STANDARD_LOAN_RENTAL = 'ADDED_STANDARD_LOAN_RENTAL'
export const STANDARD_LOAN_RENTAL = 'STANDARD_LOAN_RENTAL'
export const UPDATED_STANDARD_LOAN_RENTAL = 'UPDATED_STANDARD_LOAN_RENTAL'
